services:

  php:
    build:
      context: .
      dockerfile: ./docker_env/php/Dockerfile
    container_name: php_container
    # no need 9000 by default
#    ports:
#      - "9000:9000"   # Expose PHP-FPM port
    volumes:
      - ./:/var/www/html
      - ./docker_env/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker_env/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    environment:
      PHP_IDE_CONFIG: serverName=don_stroy
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
    networks:
      - project-net

  nginx:
    build:
      context: .
      dockerfile: ./docker_env/nginx/Dockerfile
    container_name: nginx_web
    ports:
      - 8080:80
    volumes:
      - ./docker_env/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    networks:
      - project-net

  postgres:
    container_name: postgres
    image: postgres:16.4
    environment:
#      POSTGRES_DB: ${DB_DATABASE}
#      POSTGRES_USER: ${DB_USERNAME}
#      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: don_stroy_mash
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - ./../postgres_data:/data/postgres
    ports:
      - 5432:5432
    networks:
      - project-net


  dbgate:
    container_name: dbgate
    image: dbgate/dbgate:5.5.6-alpine
    restart: always
    ports:
      - 8087:3000
    volumes:
      - ./../postgres_data:/data/postgres
    environment:
      CONNECTIONS: con1,con2,con3,con4

      LABEL_con2: Postgres
      SERVER_con2: postgres
      USER_con2: root
      PASSWORD_con2: password
      PORT_con2: 5432
      ENGINE_con2: postgres@dbgate-plugin-postgres
    networks:
      - project-net


###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

networks:
  project-net:
    driver: bridge

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
